### ISSUE TITLE
Failed in Test

### ISSUE THREAD

**Issue by kiyonlin** [cch123/supermonkey#2]
Hey thanks for the awesome package!

I met some problems when using supermonkey in test.

```go
// main.go
package main

import (
	"fmt"
)

func main() {
	heyHey()
}

//go:noinline
func heyHey() {
	fmt.Println("fake")
}
```

```go
package main

import (
	"fmt"
	"testing"

	sm "github.com/cch123/supermonkey"
)

func Test_HeyHey(t *testing.T) {
	fmt.Println("original function output:")
	heyHey()
	fmt.Println()

	sm.PatchByFullSymbolName("main.heyHey", func() {
		fmt.Println("please be polite")
	})
	fmt.Println("after patch, function output:")
	heyHey()
	fmt.Println()

	sm.UnpatchAll()
	fmt.Println("unpatch all, then output:")
	heyHey()
}
```

And I run the test like 
```bash
$go test -gcflags="-l" ./
original function output:
fake

The symbol is main.heyHey, and the patch target addr is 0, there may be 2 possible reasons
        1. the function is inlined, please add //go:noinline to function comment or add -l to gcflags
        2. your input for symbolName or pkg/obj/method is wrong, check by using go tool nm {your_bin_file}
--- FAIL: Test_HeyHey (0.00s)
panic:  [recovered]
        panic: 

goroutine 20 [running]:
testing.tRunner.func1.1(0x1193940, 0x1222350)
        /usr/local/Cellar/go/1.14.4/libexec/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc0000d0360)
        /usr/local/Cellar/go/1.14.4/libexec/src/testing/testing.go:943 +0x3f9
panic(0x1193940, 0x1222350)
        /usr/local/Cellar/go/1.14.4/libexec/src/runtime/panic.go:969 +0x166
github.com/cch123/supermonkey.PatchByFullSymbolName(0x11e749e, 0xb, 0x1191d20, 0x11f4610)
        /Users/kiyon/go/pkg/mod/github.com/cch123/supermonkey@v0.9.2/supermonkey.go:33 +0x326
learn-golang/supermonkey.Test_HeyHey(0xc0000d0360)
        /Users/kiyon/Code/learn/learn-golang/supermonkey/main_test.go:15 +0xac
testing.tRunner(0xc0000d0360, 0x11f4618)
        /usr/local/Cellar/go/1.14.4/libexec/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
        /usr/local/Cellar/go/1.14.4/libexec/src/testing/testing.go:1042 +0x357
FAIL    learn-golang/supermonkey        0.399s
FAIL
```

Did I miss something?

**Comment by momaek** [comment]
Check out https://github.com/cch123/supermonkey/blob/master/supermonkey.go#L57

**Comment by cch123** [comment]
You can try this demo first

```go
package elasttt

import (
	"fmt"
	"testing"

	"github.com/cch123/elasticsql"
	sm "github.com/cch123/supermonkey"
)

func Test_HeyHey(t *testing.T) {
	fmt.Println("original function output:")
	sql := "select * from a where i = 1"
	a, b, e := elasticsql.Convert(sql)

	fmt.Println(a, b, e)

	sm.PatchByFullSymbolName("github.com/cch123/elasticsql.Convert",
		func(sql string) (dsl string, table string, err error) {
			return "", "", nil
		})

	a, b, e = elasticsql.Convert(sql)
	fmt.Println("after patch")
	fmt.Println(a, b, e)

	sm.UnpatchAll()
	fmt.Println("after unpatch")
	a, b, e = elasticsql.Convert(sql)
	fmt.Println(a, b, e)

}
```

Give me some time to find out the reason...

**Comment by cch123** [comment]
it seems the package name generated by test is not main, for example, on my machine:

![image](https://user-images.githubusercontent.com/384546/92387700-9e0fdb00-f148-11ea-8643-5bc0d452a05d.png)

if you want to patch a function, you need to provide its full package path, I'll fix the doc as soon as possible

**Comment by kiyonlin** [comment]
Thanks for the quick response! I'll try the full package name.

**Comment by cch123** [comment]
@kiyonlin , I've done more tests on this, maybe it's hard to setup on linux. The default test binary generated by Go on linux does not have a symbol table, to make it work , I have to execute `go test -c -o xxx.test && ./xxx.test`

**Comment by kiyonlin** [comment]
Alright, this is also an approach. I'm appreciate it very much.
